apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    nodeIPAM:
      enabled: true
    l2announcements:
      enabled: true
    kubeProxyReplacement: true
    k8sServiceHost: ***********************
    k8sServicePort: 6443
